default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: trailblazer_development

test:
  <<: *default
  database: trailblazer_test

production:
  <<: *default
  adapter: postgresql
  database: trailblazer_production
